### ISSUE TITLE
输入中文关键字 无法抓取结果

### ISSUE THREAD

**Issue by idreamsoft** [henrylee2cn/pholcus#2]
2015/06/22 10:20:26 
执行任务总数（任务数[*关键词数]）为 1 个...

2015/06/22 10:20:26 
爬虫队列可容纳蜘蛛 1 只...

2015/06/22 10:20:26 
并发协程最多 20 个……

2015/06/22 10:20:26 
随机停顿时间为 1000~4000 ms ……

2015/06/22 10:20:26 *********************************************开始抓取，请耐心等候*********************************************

2015/06/22 10:20:27 start crawl : http://s.1688.com/selloffer/offer_search.htm?enableAsync=false&earseDirect=false&button_click=top&pageSize=60&n=y&offset=3&fromSycm=y&uniqfield=pic_tag_id&keywords=����&beginPage=1

2015/06/22 10:20:32 [消息提示：| 任务：阿里巴巴产品搜索 | 关键词：阀门 | 规则：生成请求] 没有抓取到任何数据！!!

2015/06/22 10:20:32 [结束报告 -> 任务：阿里巴巴产品搜索 | 关键词：阀门] 共输出数据 0 条，用时 0.10027 分钟！！！

2015/06/22 10:20:32 *****************************！！本次抓取合计 0 条数据，下载页面 1 个，耗时：0.10027 分钟！！***************************

**Comment by henrylee2cn** [comment]
你好，感谢你提出的问题，我已经改过规则了，这个只是阿里的采集规则本身问题，不属于框架问题。我把改好的阿里规则更新上来了。
![image](https://cloud.githubusercontent.com/assets/10174178/8278480/41f0dad6-18fe-11e5-9e8d-102c546afd57.png)
