### ISSUE TITLE
Support for OS X?

### ISSUE THREAD

**Issue by CatTail** [henrylee2cn/pholcus#3]

**Comment by tomcatzh** [comment]
看起来不太可能，作者用的是
https://github.com/lxn/walk
https://github.com/lxn/win

这些都是纯的windows GUI

其实mac做爬虫的机会少，linux的支持，或者webGUI倒是可以考虑

**Comment by henrylee2cn** [comment]
已经有很多人建议用webGUI了，过段时间把它换上
